//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1434.
// 
#pragma warning disable 1591

namespace Ncuhome.Blog.Core.FuncCommonReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FuncCommonServiceSoap", Namespace="http://tempuri.org/")]
    public partial class FuncCommonService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetManageridByFIIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFiidByUserIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllUserProfilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserProfilebyUserTxzIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback getXSJBXXByXhOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumberByTxzIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTxzIDByNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTxzIDByTxzOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUIDByTxzidOperationCompleted;
        
        private System.Threading.SendOrPostCallback GettruenameIDByTxzidOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBJJBXXByBhOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FuncCommonService() {
            this.Url = global::Ncuhome.Blog.Core.Properties.Settings.Default.Blog_Core_FuncCommonReference_FuncCommonService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetManageridByFIIDCompletedEventHandler GetManageridByFIIDCompleted;
        
        /// <remarks/>
        public event GetFiidByUserIdCompletedEventHandler GetFiidByUserIdCompleted;
        
        /// <remarks/>
        public event getAllUserProfilesCompletedEventHandler getAllUserProfilesCompleted;
        
        /// <remarks/>
        public event getUserProfilebyUserTxzIDCompletedEventHandler getUserProfilebyUserTxzIDCompleted;
        
        /// <remarks/>
        public event SetUserProfileCompletedEventHandler SetUserProfileCompleted;
        
        /// <remarks/>
        public event getXSJBXXByXhCompletedEventHandler getXSJBXXByXhCompleted;
        
        /// <remarks/>
        public event GetNumberByTxzIDCompletedEventHandler GetNumberByTxzIDCompleted;
        
        /// <remarks/>
        public event GetTxzIDByNumberCompletedEventHandler GetTxzIDByNumberCompleted;
        
        /// <remarks/>
        public event GetTxzIDByTxzCompletedEventHandler GetTxzIDByTxzCompleted;
        
        /// <remarks/>
        public event GetUIDByTxzidCompletedEventHandler GetUIDByTxzidCompleted;
        
        /// <remarks/>
        public event GettruenameIDByTxzidCompletedEventHandler GettruenameIDByTxzidCompleted;
        
        /// <remarks/>
        public event getBJJBXXByBhCompletedEventHandler getBJJBXXByBhCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetManageridByFIID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetManageridByFIID(int Fiid) {
            object[] results = this.Invoke("GetManageridByFIID", new object[] {
                        Fiid});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetManageridByFIIDAsync(int Fiid) {
            this.GetManageridByFIIDAsync(Fiid, null);
        }
        
        /// <remarks/>
        public void GetManageridByFIIDAsync(int Fiid, object userState) {
            if ((this.GetManageridByFIIDOperationCompleted == null)) {
                this.GetManageridByFIIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetManageridByFIIDOperationCompleted);
            }
            this.InvokeAsync("GetManageridByFIID", new object[] {
                        Fiid}, this.GetManageridByFIIDOperationCompleted, userState);
        }
        
        private void OnGetManageridByFIIDOperationCompleted(object arg) {
            if ((this.GetManageridByFIIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetManageridByFIIDCompleted(this, new GetManageridByFIIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFiidByUserId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetFiidByUserId(int OwnerID, int modid, int funcid) {
            object[] results = this.Invoke("GetFiidByUserId", new object[] {
                        OwnerID,
                        modid,
                        funcid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetFiidByUserIdAsync(int OwnerID, int modid, int funcid) {
            this.GetFiidByUserIdAsync(OwnerID, modid, funcid, null);
        }
        
        /// <remarks/>
        public void GetFiidByUserIdAsync(int OwnerID, int modid, int funcid, object userState) {
            if ((this.GetFiidByUserIdOperationCompleted == null)) {
                this.GetFiidByUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFiidByUserIdOperationCompleted);
            }
            this.InvokeAsync("GetFiidByUserId", new object[] {
                        OwnerID,
                        modid,
                        funcid}, this.GetFiidByUserIdOperationCompleted, userState);
        }
        
        private void OnGetFiidByUserIdOperationCompleted(object arg) {
            if ((this.GetFiidByUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFiidByUserIdCompleted(this, new GetFiidByUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllUserProfiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserProfile[] getAllUserProfiles() {
            object[] results = this.Invoke("getAllUserProfiles", new object[0]);
            return ((UserProfile[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllUserProfilesAsync() {
            this.getAllUserProfilesAsync(null);
        }
        
        /// <remarks/>
        public void getAllUserProfilesAsync(object userState) {
            if ((this.getAllUserProfilesOperationCompleted == null)) {
                this.getAllUserProfilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllUserProfilesOperationCompleted);
            }
            this.InvokeAsync("getAllUserProfiles", new object[0], this.getAllUserProfilesOperationCompleted, userState);
        }
        
        private void OngetAllUserProfilesOperationCompleted(object arg) {
            if ((this.getAllUserProfilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllUserProfilesCompleted(this, new getAllUserProfilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserProfilebyUserTxzID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserProfile getUserProfilebyUserTxzID(int TxzID) {
            object[] results = this.Invoke("getUserProfilebyUserTxzID", new object[] {
                        TxzID});
            return ((UserProfile)(results[0]));
        }
        
        /// <remarks/>
        public void getUserProfilebyUserTxzIDAsync(int TxzID) {
            this.getUserProfilebyUserTxzIDAsync(TxzID, null);
        }
        
        /// <remarks/>
        public void getUserProfilebyUserTxzIDAsync(int TxzID, object userState) {
            if ((this.getUserProfilebyUserTxzIDOperationCompleted == null)) {
                this.getUserProfilebyUserTxzIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserProfilebyUserTxzIDOperationCompleted);
            }
            this.InvokeAsync("getUserProfilebyUserTxzID", new object[] {
                        TxzID}, this.getUserProfilebyUserTxzIDOperationCompleted, userState);
        }
        
        private void OngetUserProfilebyUserTxzIDOperationCompleted(object arg) {
            if ((this.getUserProfilebyUserTxzIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserProfilebyUserTxzIDCompleted(this, new getUserProfilebyUserTxzIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetUserProfile(UserProfile up) {
            this.Invoke("SetUserProfile", new object[] {
                        up});
        }
        
        /// <remarks/>
        public void SetUserProfileAsync(UserProfile up) {
            this.SetUserProfileAsync(up, null);
        }
        
        /// <remarks/>
        public void SetUserProfileAsync(UserProfile up, object userState) {
            if ((this.SetUserProfileOperationCompleted == null)) {
                this.SetUserProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserProfileOperationCompleted);
            }
            this.InvokeAsync("SetUserProfile", new object[] {
                        up}, this.SetUserProfileOperationCompleted, userState);
        }
        
        private void OnSetUserProfileOperationCompleted(object arg) {
            if ((this.SetUserProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserProfileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getXSJBXXByXh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public XSJBXX getXSJBXXByXh(string xh) {
            object[] results = this.Invoke("getXSJBXXByXh", new object[] {
                        xh});
            return ((XSJBXX)(results[0]));
        }
        
        /// <remarks/>
        public void getXSJBXXByXhAsync(string xh) {
            this.getXSJBXXByXhAsync(xh, null);
        }
        
        /// <remarks/>
        public void getXSJBXXByXhAsync(string xh, object userState) {
            if ((this.getXSJBXXByXhOperationCompleted == null)) {
                this.getXSJBXXByXhOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetXSJBXXByXhOperationCompleted);
            }
            this.InvokeAsync("getXSJBXXByXh", new object[] {
                        xh}, this.getXSJBXXByXhOperationCompleted, userState);
        }
        
        private void OngetXSJBXXByXhOperationCompleted(object arg) {
            if ((this.getXSJBXXByXhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getXSJBXXByXhCompleted(this, new getXSJBXXByXhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumberByTxzID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNumberByTxzID(int id) {
            object[] results = this.Invoke("GetNumberByTxzID", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumberByTxzIDAsync(int id) {
            this.GetNumberByTxzIDAsync(id, null);
        }
        
        /// <remarks/>
        public void GetNumberByTxzIDAsync(int id, object userState) {
            if ((this.GetNumberByTxzIDOperationCompleted == null)) {
                this.GetNumberByTxzIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumberByTxzIDOperationCompleted);
            }
            this.InvokeAsync("GetNumberByTxzID", new object[] {
                        id}, this.GetNumberByTxzIDOperationCompleted, userState);
        }
        
        private void OnGetNumberByTxzIDOperationCompleted(object arg) {
            if ((this.GetNumberByTxzIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumberByTxzIDCompleted(this, new GetNumberByTxzIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTxzIDByNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetTxzIDByNumber(string number) {
            object[] results = this.Invoke("GetTxzIDByNumber", new object[] {
                        number});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetTxzIDByNumberAsync(string number) {
            this.GetTxzIDByNumberAsync(number, null);
        }
        
        /// <remarks/>
        public void GetTxzIDByNumberAsync(string number, object userState) {
            if ((this.GetTxzIDByNumberOperationCompleted == null)) {
                this.GetTxzIDByNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTxzIDByNumberOperationCompleted);
            }
            this.InvokeAsync("GetTxzIDByNumber", new object[] {
                        number}, this.GetTxzIDByNumberOperationCompleted, userState);
        }
        
        private void OnGetTxzIDByNumberOperationCompleted(object arg) {
            if ((this.GetTxzIDByNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTxzIDByNumberCompleted(this, new GetTxzIDByNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTxzIDByTxz", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetTxzIDByTxz(string txz) {
            object[] results = this.Invoke("GetTxzIDByTxz", new object[] {
                        txz});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetTxzIDByTxzAsync(string txz) {
            this.GetTxzIDByTxzAsync(txz, null);
        }
        
        /// <remarks/>
        public void GetTxzIDByTxzAsync(string txz, object userState) {
            if ((this.GetTxzIDByTxzOperationCompleted == null)) {
                this.GetTxzIDByTxzOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTxzIDByTxzOperationCompleted);
            }
            this.InvokeAsync("GetTxzIDByTxz", new object[] {
                        txz}, this.GetTxzIDByTxzOperationCompleted, userState);
        }
        
        private void OnGetTxzIDByTxzOperationCompleted(object arg) {
            if ((this.GetTxzIDByTxzCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTxzIDByTxzCompleted(this, new GetTxzIDByTxzCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUIDByTxzid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUIDByTxzid(int txzid) {
            object[] results = this.Invoke("GetUIDByTxzid", new object[] {
                        txzid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUIDByTxzidAsync(int txzid) {
            this.GetUIDByTxzidAsync(txzid, null);
        }
        
        /// <remarks/>
        public void GetUIDByTxzidAsync(int txzid, object userState) {
            if ((this.GetUIDByTxzidOperationCompleted == null)) {
                this.GetUIDByTxzidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUIDByTxzidOperationCompleted);
            }
            this.InvokeAsync("GetUIDByTxzid", new object[] {
                        txzid}, this.GetUIDByTxzidOperationCompleted, userState);
        }
        
        private void OnGetUIDByTxzidOperationCompleted(object arg) {
            if ((this.GetUIDByTxzidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUIDByTxzidCompleted(this, new GetUIDByTxzidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GettruenameIDByTxzid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GettruenameIDByTxzid(int id) {
            object[] results = this.Invoke("GettruenameIDByTxzid", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GettruenameIDByTxzidAsync(int id) {
            this.GettruenameIDByTxzidAsync(id, null);
        }
        
        /// <remarks/>
        public void GettruenameIDByTxzidAsync(int id, object userState) {
            if ((this.GettruenameIDByTxzidOperationCompleted == null)) {
                this.GettruenameIDByTxzidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGettruenameIDByTxzidOperationCompleted);
            }
            this.InvokeAsync("GettruenameIDByTxzid", new object[] {
                        id}, this.GettruenameIDByTxzidOperationCompleted, userState);
        }
        
        private void OnGettruenameIDByTxzidOperationCompleted(object arg) {
            if ((this.GettruenameIDByTxzidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GettruenameIDByTxzidCompleted(this, new GettruenameIDByTxzidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getBJJBXXByBh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BJJBXX getBJJBXXByBh(string bh) {
            object[] results = this.Invoke("getBJJBXXByBh", new object[] {
                        bh});
            return ((BJJBXX)(results[0]));
        }
        
        /// <remarks/>
        public void getBJJBXXByBhAsync(string bh) {
            this.getBJJBXXByBhAsync(bh, null);
        }
        
        /// <remarks/>
        public void getBJJBXXByBhAsync(string bh, object userState) {
            if ((this.getBJJBXXByBhOperationCompleted == null)) {
                this.getBJJBXXByBhOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBJJBXXByBhOperationCompleted);
            }
            this.InvokeAsync("getBJJBXXByBh", new object[] {
                        bh}, this.getBJJBXXByBhOperationCompleted, userState);
        }
        
        private void OngetBJJBXXByBhOperationCompleted(object arg) {
            if ((this.getBJJBXXByBhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBJJBXXByBhCompleted(this, new getBJJBXXByBhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserProfile {
        
        private int idField;
        
        private int tXZIDField;
        
        private int themeIdField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int TXZID {
            get {
                return this.tXZIDField;
            }
            set {
                this.tXZIDField = value;
            }
        }
        
        /// <remarks/>
        public int ThemeId {
            get {
                return this.themeIdField;
            }
            set {
                this.themeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BJJBXX {
        
        private string bhField;
        
        private string bJMCField;
        
        private string zYMCField;
        
        private string xYMCField;
        
        /// <remarks/>
        public string BH {
            get {
                return this.bhField;
            }
            set {
                this.bhField = value;
            }
        }
        
        /// <remarks/>
        public string BJMC {
            get {
                return this.bJMCField;
            }
            set {
                this.bJMCField = value;
            }
        }
        
        /// <remarks/>
        public string ZYMC {
            get {
                return this.zYMCField;
            }
            set {
                this.zYMCField = value;
            }
        }
        
        /// <remarks/>
        public string XYMC {
            get {
                return this.xYMCField;
            }
            set {
                this.xYMCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class XSJBXX {
        
        private string xhField;
        
        private string xmField;
        
        private string bhField;
        
        private string bJMCField;
        
        private string njField;
        
        private string rXNYField;
        
        private string cSRQField;
        
        private string qSHField;
        
        private string zYMCField;
        
        private string xYMCField;
        
        private string xbField;
        
        private string mzField;
        
        private string sfField;
        
        private string sFZHField;
        
        /// <remarks/>
        public string XH {
            get {
                return this.xhField;
            }
            set {
                this.xhField = value;
            }
        }
        
        /// <remarks/>
        public string XM {
            get {
                return this.xmField;
            }
            set {
                this.xmField = value;
            }
        }
        
        /// <remarks/>
        public string BH {
            get {
                return this.bhField;
            }
            set {
                this.bhField = value;
            }
        }
        
        /// <remarks/>
        public string BJMC {
            get {
                return this.bJMCField;
            }
            set {
                this.bJMCField = value;
            }
        }
        
        /// <remarks/>
        public string NJ {
            get {
                return this.njField;
            }
            set {
                this.njField = value;
            }
        }
        
        /// <remarks/>
        public string RXNY {
            get {
                return this.rXNYField;
            }
            set {
                this.rXNYField = value;
            }
        }
        
        /// <remarks/>
        public string CSRQ {
            get {
                return this.cSRQField;
            }
            set {
                this.cSRQField = value;
            }
        }
        
        /// <remarks/>
        public string QSH {
            get {
                return this.qSHField;
            }
            set {
                this.qSHField = value;
            }
        }
        
        /// <remarks/>
        public string ZYMC {
            get {
                return this.zYMCField;
            }
            set {
                this.zYMCField = value;
            }
        }
        
        /// <remarks/>
        public string XYMC {
            get {
                return this.xYMCField;
            }
            set {
                this.xYMCField = value;
            }
        }
        
        /// <remarks/>
        public string XB {
            get {
                return this.xbField;
            }
            set {
                this.xbField = value;
            }
        }
        
        /// <remarks/>
        public string MZ {
            get {
                return this.mzField;
            }
            set {
                this.mzField = value;
            }
        }
        
        /// <remarks/>
        public string SF {
            get {
                return this.sfField;
            }
            set {
                this.sfField = value;
            }
        }
        
        /// <remarks/>
        public string SFZH {
            get {
                return this.sFZHField;
            }
            set {
                this.sFZHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetManageridByFIIDCompletedEventHandler(object sender, GetManageridByFIIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetManageridByFIIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetManageridByFIIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetFiidByUserIdCompletedEventHandler(object sender, GetFiidByUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFiidByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFiidByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void getAllUserProfilesCompletedEventHandler(object sender, getAllUserProfilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllUserProfilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllUserProfilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserProfile[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserProfile[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void getUserProfilebyUserTxzIDCompletedEventHandler(object sender, getUserProfilebyUserTxzIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserProfilebyUserTxzIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserProfilebyUserTxzIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserProfile Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserProfile)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void SetUserProfileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void getXSJBXXByXhCompletedEventHandler(object sender, getXSJBXXByXhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getXSJBXXByXhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getXSJBXXByXhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public XSJBXX Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((XSJBXX)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetNumberByTxzIDCompletedEventHandler(object sender, GetNumberByTxzIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumberByTxzIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumberByTxzIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetTxzIDByNumberCompletedEventHandler(object sender, GetTxzIDByNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTxzIDByNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTxzIDByNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetTxzIDByTxzCompletedEventHandler(object sender, GetTxzIDByTxzCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTxzIDByTxzCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTxzIDByTxzCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetUIDByTxzidCompletedEventHandler(object sender, GetUIDByTxzidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUIDByTxzidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUIDByTxzidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GettruenameIDByTxzidCompletedEventHandler(object sender, GettruenameIDByTxzidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GettruenameIDByTxzidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GettruenameIDByTxzidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void getBJJBXXByBhCompletedEventHandler(object sender, getBJJBXXByBhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBJJBXXByBhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBJJBXXByBhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BJJBXX Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BJJBXX)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591