
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace Ncuhome.Blog.Entity 
{
    /// <summary>
    /// The class representing the dbo.Weblog_GroupComment table.
    /// </summary>
    [Table(Name="dbo.Weblog_GroupComment")]
    public partial class Weblog_GroupComment
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Weblog_GroupComment"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public Weblog_GroupComment()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private long _GC_Id = default(long);

        /// <summary>
        /// Gets the GC_Id column value.
        /// </summary>
        [Column(Name="GC_Id", Storage="_GC_Id", DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, CanBeNull=false)]
        public long GC_Id
        {
            get { return _GC_Id; }
            set
            {
                if (_GC_Id != value)
                {
                    OnGC_IdChanging(value);
                    _GC_Id = value;
                    OnGC_IdChanged();
                }
            }
        }
        
        private long _GC_UserId;

        /// <summary>
        /// Gets or sets the GC_UserId column value.
        /// </summary>
        [Column(Name="GC_UserId", Storage="_GC_UserId", DbType="BigInt NOT NULL", CanBeNull=false)]
        public long GC_UserId
        {
            get { return _GC_UserId; }
            set
            {
                if (_GC_UserId != value)
                {
                    OnGC_UserIdChanging(value);
                    _GC_UserId = value;
                    OnGC_UserIdChanged();
                }
            }
        }
        
        private Nullable<long> _GC_ToCommentId;

        /// <summary>
        /// Gets or sets the GC_ToCommentId column value.
        /// </summary>
        [Column(Name="GC_ToCommentId", Storage="_GC_ToCommentId", DbType="BigInt")]
        public Nullable<long> GC_ToCommentId
        {
            get { return _GC_ToCommentId; }
            set
            {
                if (_GC_ToCommentId != value)
                {
                    OnGC_ToCommentIdChanging(value);
                    _GC_ToCommentId = value;
                    OnGC_ToCommentIdChanged();
                }
            }
        }
        
        private long _GC_LogId;

        /// <summary>
        /// Gets or sets the GC_LogId column value.
        /// </summary>
        [Column(Name="GC_LogId", Storage="_GC_LogId", DbType="BigInt NOT NULL", CanBeNull=false)]
        public long GC_LogId
        {
            get { return _GC_LogId; }
            set
            {
                if (_GC_LogId != value)
                {
                    OnGC_LogIdChanging(value);
                    _GC_LogId = value;
                    OnGC_LogIdChanged();
                }
            }
        }
        
        private string _GC_Content;

        /// <summary>
        /// Gets or sets the GC_Content column value.
        /// </summary>
        [Column(Name="GC_Content", Storage="_GC_Content", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
        public string GC_Content
        {
            get { return _GC_Content; }
            set
            {
                if (_GC_Content != value)
                {
                    OnGC_ContentChanging(value);
                    _GC_Content = value;
                    OnGC_ContentChanged();
                }
            }
        }
        
        private System.DateTime _GC_CreateTime;

        /// <summary>
        /// Gets or sets the GC_CreateTime column value.
        /// </summary>
        [Column(Name="GC_CreateTime", Storage="_GC_CreateTime", DbType="DateTime NOT NULL", CanBeNull=false)]
        public System.DateTime GC_CreateTime
        {
            get { return _GC_CreateTime; }
            set
            {
                if (_GC_CreateTime != value)
                {
                    OnGC_CreateTimeChanging(value);
                    _GC_CreateTime = value;
                    OnGC_CreateTimeChanged();
                }
            }
        }
        
        private long _GC_GroupTopicId;

        /// <summary>
        /// Gets or sets the GC_GroupTopicId column value.
        /// </summary>
        [Column(Name="GC_GroupTopicId", Storage="_GC_GroupTopicId", DbType="BigInt NOT NULL", CanBeNull=false)]
        public long GC_GroupTopicId
        {
            get { return _GC_GroupTopicId; }
            set
            {
                if (_GC_GroupTopicId != value)
                {
                    OnGC_GroupTopicIdChanging(value);
                    _GC_GroupTopicId = value;
                    OnGC_GroupTopicIdChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when GC_Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnGC_IdChanging(long value);
        /// <summary>Called after GC_Id has Changed.</summary>
        partial void OnGC_IdChanged();
        /// <summary>Called when GC_UserId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnGC_UserIdChanging(long value);
        /// <summary>Called after GC_UserId has Changed.</summary>
        partial void OnGC_UserIdChanged();
        /// <summary>Called when GC_ToCommentId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnGC_ToCommentIdChanging(Nullable<long> value);
        /// <summary>Called after GC_ToCommentId has Changed.</summary>
        partial void OnGC_ToCommentIdChanged();
        /// <summary>Called when GC_LogId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnGC_LogIdChanging(long value);
        /// <summary>Called after GC_LogId has Changed.</summary>
        partial void OnGC_LogIdChanged();
        /// <summary>Called when GC_Content is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnGC_ContentChanging(string value);
        /// <summary>Called after GC_Content has Changed.</summary>
        partial void OnGC_ContentChanged();
        /// <summary>Called when GC_CreateTime is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnGC_CreateTimeChanging(System.DateTime value);
        /// <summary>Called after GC_CreateTime has Changed.</summary>
        partial void OnGC_CreateTimeChanged();
        /// <summary>Called when GC_GroupTopicId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnGC_GroupTopicIdChanging(long value);
        /// <summary>Called after GC_GroupTopicId has Changed.</summary>
        partial void OnGC_GroupTopicIdChanged();
        #endregion
        
    }
}

