
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace Ncuhome.Blog.Entity 
{
    /// <summary>
    /// The class representing the dbo.Weblog_ViewLog table.
    /// </summary>
    [Table(Name="dbo.Weblog_ViewLog")]
    public partial class Weblog_ViewLog
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Weblog_ViewLog"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public Weblog_ViewLog()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private int _ViewLog_Id = default(int);

        /// <summary>
        /// Gets the ViewLog_Id column value.
        /// </summary>
        [Column(Name="ViewLog_Id", Storage="_ViewLog_Id", DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, CanBeNull=false)]
        public int ViewLog_Id
        {
            get { return _ViewLog_Id; }
            set
            {
                if (_ViewLog_Id != value)
                {
                    OnViewLog_IdChanging(value);
                    _ViewLog_Id = value;
                    OnViewLog_IdChanged();
                }
            }
        }
        
        private int _ViewLog_UserId;

        /// <summary>
        /// Gets or sets the ViewLog_UserId column value.
        /// </summary>
        [Column(Name="ViewLog_UserId", Storage="_ViewLog_UserId", DbType="Int NOT NULL", CanBeNull=false)]
        public int ViewLog_UserId
        {
            get { return _ViewLog_UserId; }
            set
            {
                if (_ViewLog_UserId != value)
                {
                    OnViewLog_UserIdChanging(value);
                    _ViewLog_UserId = value;
                    OnViewLog_UserIdChanged();
                }
            }
        }
        
        private int _ViewLog_LogId;

        /// <summary>
        /// Gets or sets the ViewLog_LogId column value.
        /// </summary>
        [Column(Name="ViewLog_LogId", Storage="_ViewLog_LogId", DbType="Int NOT NULL", CanBeNull=false)]
        public int ViewLog_LogId
        {
            get { return _ViewLog_LogId; }
            set
            {
                if (_ViewLog_LogId != value)
                {
                    OnViewLog_LogIdChanging(value);
                    _ViewLog_LogId = value;
                    OnViewLog_LogIdChanged();
                }
            }
        }
        
        private System.DateTime _ViewLog_CreateTime;

        /// <summary>
        /// Gets or sets the ViewLog_CreateTime column value.
        /// </summary>
        [Column(Name="ViewLog_CreateTime", Storage="_ViewLog_CreateTime", DbType="DateTime NOT NULL", CanBeNull=false)]
        public System.DateTime ViewLog_CreateTime
        {
            get { return _ViewLog_CreateTime; }
            set
            {
                if (_ViewLog_CreateTime != value)
                {
                    OnViewLog_CreateTimeChanging(value);
                    _ViewLog_CreateTime = value;
                    OnViewLog_CreateTimeChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when ViewLog_Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnViewLog_IdChanging(int value);
        /// <summary>Called after ViewLog_Id has Changed.</summary>
        partial void OnViewLog_IdChanged();
        /// <summary>Called when ViewLog_UserId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnViewLog_UserIdChanging(int value);
        /// <summary>Called after ViewLog_UserId has Changed.</summary>
        partial void OnViewLog_UserIdChanged();
        /// <summary>Called when ViewLog_LogId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnViewLog_LogIdChanging(int value);
        /// <summary>Called after ViewLog_LogId has Changed.</summary>
        partial void OnViewLog_LogIdChanged();
        /// <summary>Called when ViewLog_CreateTime is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnViewLog_CreateTimeChanging(System.DateTime value);
        /// <summary>Called after ViewLog_CreateTime has Changed.</summary>
        partial void OnViewLog_CreateTimeChanged();
        #endregion
        
    }
}

