
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace Ncuhome.Blog.Entity
{
    /// <summary>
    /// The class representing the dbo.View_WeblogUserRecommend table.
    /// </summary>
    [Table(Name="dbo.View_WeblogUserRecommend")]
    public partial class View_WeblogUserRecommend
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="View_WeblogUserRecommend"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public View_WeblogUserRecommend()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private int _Recommend_Id;

        /// <summary>
        /// Gets or sets the Recommend_Id column value.
        /// </summary>
        [Column(Name="Recommend_Id", Storage="_Recommend_Id", DbType="Int NOT NULL", CanBeNull=false)]
        public int Recommend_Id
        {
            get { return _Recommend_Id; }
            set
            {
                if (_Recommend_Id != value)
                {
                    OnRecommend_IdChanging(value);
                    _Recommend_Id = value;
                    OnRecommend_IdChanged();
                }
            }
        }
        
        private int _Recommend_LogId;

        /// <summary>
        /// Gets or sets the Recommend_LogId column value.
        /// </summary>
        [Column(Name="Recommend_LogId", Storage="_Recommend_LogId", DbType="Int NOT NULL", CanBeNull=false)]
        public int Recommend_LogId
        {
            get { return _Recommend_LogId; }
            set
            {
                if (_Recommend_LogId != value)
                {
                    OnRecommend_LogIdChanging(value);
                    _Recommend_LogId = value;
                    OnRecommend_LogIdChanged();
                }
            }
        }
        
        private System.DateTime _Recommend_CreateTime;

        /// <summary>
        /// Gets or sets the Recommend_CreateTime column value.
        /// </summary>
        [Column(Name="Recommend_CreateTime", Storage="_Recommend_CreateTime", DbType="DateTime NOT NULL", CanBeNull=false)]
        public System.DateTime Recommend_CreateTime
        {
            get { return _Recommend_CreateTime; }
            set
            {
                if (_Recommend_CreateTime != value)
                {
                    OnRecommend_CreateTimeChanging(value);
                    _Recommend_CreateTime = value;
                    OnRecommend_CreateTimeChanged();
                }
            }
        }
        
        private int _User_Id;

        /// <summary>
        /// Gets or sets the User_Id column value.
        /// </summary>
        [Column(Name="User_Id", Storage="_User_Id", DbType="Int NOT NULL", CanBeNull=false)]
        public int User_Id
        {
            get { return _User_Id; }
            set
            {
                if (_User_Id != value)
                {
                    OnUser_IdChanging(value);
                    _User_Id = value;
                    OnUser_IdChanged();
                }
            }
        }
        
        private string _User_NickName;

        /// <summary>
        /// Gets or sets the User_NickName column value.
        /// </summary>
        [Column(Name="User_NickName", Storage="_User_NickName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
        public string User_NickName
        {
            get { return _User_NickName; }
            set
            {
                if (_User_NickName != value)
                {
                    OnUser_NickNameChanging(value);
                    _User_NickName = value;
                    OnUser_NickNameChanged();
                }
            }
        }
        
        private string _User_PortraitUrl;

        /// <summary>
        /// Gets or sets the User_PortraitUrl column value.
        /// </summary>
        [Column(Name="User_PortraitUrl", Storage="_User_PortraitUrl", DbType="NVarChar(50)")]
        public string User_PortraitUrl
        {
            get { return _User_PortraitUrl; }
            set
            {
                if (_User_PortraitUrl != value)
                {
                    OnUser_PortraitUrlChanging(value);
                    _User_PortraitUrl = value;
                    OnUser_PortraitUrlChanged();
                }
            }
        }
        
        private int _Log_Id;

        /// <summary>
        /// Gets or sets the Log_Id column value.
        /// </summary>
        [Column(Name="Log_Id", Storage="_Log_Id", DbType="Int NOT NULL", CanBeNull=false)]
        public int Log_Id
        {
            get { return _Log_Id; }
            set
            {
                if (_Log_Id != value)
                {
                    OnLog_IdChanging(value);
                    _Log_Id = value;
                    OnLog_IdChanged();
                }
            }
        }
        
        private Nullable<int> _Log_UserId;

        /// <summary>
        /// Gets or sets the Log_UserId column value.
        /// </summary>
        [Column(Name="Log_UserId", Storage="_Log_UserId", DbType="Int")]
        public Nullable<int> Log_UserId
        {
            get { return _Log_UserId; }
            set
            {
                if (_Log_UserId != value)
                {
                    OnLog_UserIdChanging(value);
                    _Log_UserId = value;
                    OnLog_UserIdChanged();
                }
            }
        }
        
        private string _Log_Title;

        /// <summary>
        /// Gets or sets the Log_Title column value.
        /// </summary>
        [Column(Name="Log_Title", Storage="_Log_Title", DbType="NVarChar(255)")]
        public string Log_Title
        {
            get { return _Log_Title; }
            set
            {
                if (_Log_Title != value)
                {
                    OnLog_TitleChanging(value);
                    _Log_Title = value;
                    OnLog_TitleChanged();
                }
            }
        }
        
        private string _Log_Content;

        /// <summary>
        /// Gets or sets the Log_Content column value.
        /// </summary>
        [Column(Name="Log_Content", Storage="_Log_Content", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
        public string Log_Content
        {
            get { return _Log_Content; }
            set
            {
                if (_Log_Content != value)
                {
                    OnLog_ContentChanging(value);
                    _Log_Content = value;
                    OnLog_ContentChanged();
                }
            }
        }
        
        private System.DateTime _Log_CreateTime;

        /// <summary>
        /// Gets or sets the Log_CreateTime column value.
        /// </summary>
        [Column(Name="Log_CreateTime", Storage="_Log_CreateTime", DbType="DateTime NOT NULL", CanBeNull=false)]
        public System.DateTime Log_CreateTime
        {
            get { return _Log_CreateTime; }
            set
            {
                if (_Log_CreateTime != value)
                {
                    OnLog_CreateTimeChanging(value);
                    _Log_CreateTime = value;
                    OnLog_CreateTimeChanged();
                }
            }
        }
        
        private Nullable<int> _Log_ViewCount;

        /// <summary>
        /// Gets or sets the Log_ViewCount column value.
        /// </summary>
        [Column(Name="Log_ViewCount", Storage="_Log_ViewCount", DbType="Int")]
        public Nullable<int> Log_ViewCount
        {
            get { return _Log_ViewCount; }
            set
            {
                if (_Log_ViewCount != value)
                {
                    OnLog_ViewCountChanging(value);
                    _Log_ViewCount = value;
                    OnLog_ViewCountChanged();
                }
            }
        }
        
        private Nullable<int> _Log_CommentCount;

        /// <summary>
        /// Gets or sets the Log_CommentCount column value.
        /// </summary>
        [Column(Name="Log_CommentCount", Storage="_Log_CommentCount", DbType="Int")]
        public Nullable<int> Log_CommentCount
        {
            get { return _Log_CommentCount; }
            set
            {
                if (_Log_CommentCount != value)
                {
                    OnLog_CommentCountChanging(value);
                    _Log_CommentCount = value;
                    OnLog_CommentCountChanged();
                }
            }
        }
        
        private Nullable<int> _Log_RecommendCount;

        /// <summary>
        /// Gets or sets the Log_RecommendCount column value.
        /// </summary>
        [Column(Name="Log_RecommendCount", Storage="_Log_RecommendCount", DbType="Int")]
        public Nullable<int> Log_RecommendCount
        {
            get { return _Log_RecommendCount; }
            set
            {
                if (_Log_RecommendCount != value)
                {
                    OnLog_RecommendCountChanging(value);
                    _Log_RecommendCount = value;
                    OnLog_RecommendCountChanged();
                }
            }
        }
        
        private Nullable<bool> _Log_IsVisible;

        /// <summary>
        /// Gets or sets the Log_IsVisible column value.
        /// </summary>
        [Column(Name="Log_IsVisible", Storage="_Log_IsVisible", DbType="Bit")]
        public Nullable<bool> Log_IsVisible
        {
            get { return _Log_IsVisible; }
            set
            {
                if (_Log_IsVisible != value)
                {
                    OnLog_IsVisibleChanging(value);
                    _Log_IsVisible = value;
                    OnLog_IsVisibleChanged();
                }
            }
        }
        
        private int _User_FIID;

        /// <summary>
        /// Gets or sets the User_FIID column value.
        /// </summary>
        [Column(Name="User_FIID", Storage="_User_FIID", DbType="Int NOT NULL", CanBeNull=false)]
        public int User_FIID
        {
            get { return _User_FIID; }
            set
            {
                if (_User_FIID != value)
                {
                    OnUser_FIIDChanging(value);
                    _User_FIID = value;
                    OnUser_FIIDChanged();
                }
            }
        }
        
        private string _User_DomainName;

        /// <summary>
        /// Gets or sets the User_DomainName column value.
        /// </summary>
        [Column(Name="User_DomainName", Storage="_User_DomainName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
        public string User_DomainName
        {
            get { return _User_DomainName; }
            set
            {
                if (_User_DomainName != value)
                {
                    OnUser_DomainNameChanging(value);
                    _User_DomainName = value;
                    OnUser_DomainNameChanged();
                }
            }
        }
        
        private Nullable<bool> _Log_IsPasssword;

        /// <summary>
        /// Gets or sets the Log_IsPasssword column value.
        /// </summary>
        [Column(Name="Log_IsPasssword", Storage="_Log_IsPasssword", DbType="Bit")]
        public Nullable<bool> Log_IsPasssword
        {
            get { return _Log_IsPasssword; }
            set
            {
                if (_Log_IsPasssword != value)
                {
                    OnLog_IsPassswordChanging(value);
                    _Log_IsPasssword = value;
                    OnLog_IsPassswordChanged();
                }
            }
        }
        
        private Nullable<bool> _Log_IsDraft;

        /// <summary>
        /// Gets or sets the Log_IsDraft column value.
        /// </summary>
        [Column(Name="Log_IsDraft", Storage="_Log_IsDraft", DbType="Bit")]
        public Nullable<bool> Log_IsDraft
        {
            get { return _Log_IsDraft; }
            set
            {
                if (_Log_IsDraft != value)
                {
                    OnLog_IsDraftChanging(value);
                    _Log_IsDraft = value;
                    OnLog_IsDraftChanged();
                }
            }
        }
        
        private Nullable<int> _Recommend_ThemeId;

        /// <summary>
        /// Gets or sets the Recommend_ThemeId column value.
        /// </summary>
        [Column(Name="Recommend_ThemeId", Storage="_Recommend_ThemeId", DbType="Int")]
        public Nullable<int> Recommend_ThemeId
        {
            get { return _Recommend_ThemeId; }
            set
            {
                if (_Recommend_ThemeId != value)
                {
                    OnRecommend_ThemeIdChanging(value);
                    _Recommend_ThemeId = value;
                    OnRecommend_ThemeIdChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when Recommend_Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnRecommend_IdChanging(int value);
        /// <summary>Called after Recommend_Id has Changed.</summary>
        partial void OnRecommend_IdChanged();
        /// <summary>Called when Recommend_LogId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnRecommend_LogIdChanging(int value);
        /// <summary>Called after Recommend_LogId has Changed.</summary>
        partial void OnRecommend_LogIdChanged();
        /// <summary>Called when Recommend_CreateTime is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnRecommend_CreateTimeChanging(System.DateTime value);
        /// <summary>Called after Recommend_CreateTime has Changed.</summary>
        partial void OnRecommend_CreateTimeChanged();
        /// <summary>Called when User_Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_IdChanging(int value);
        /// <summary>Called after User_Id has Changed.</summary>
        partial void OnUser_IdChanged();
        /// <summary>Called when User_NickName is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_NickNameChanging(string value);
        /// <summary>Called after User_NickName has Changed.</summary>
        partial void OnUser_NickNameChanged();
        /// <summary>Called when User_PortraitUrl is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_PortraitUrlChanging(string value);
        /// <summary>Called after User_PortraitUrl has Changed.</summary>
        partial void OnUser_PortraitUrlChanged();
        /// <summary>Called when Log_Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnLog_IdChanging(int value);
        /// <summary>Called after Log_Id has Changed.</summary>
        partial void OnLog_IdChanged();
        /// <summary>Called when Log_UserId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnLog_UserIdChanging(Nullable<int> value);
        /// <summary>Called after Log_UserId has Changed.</summary>
        partial void OnLog_UserIdChanged();
        /// <summary>Called when Log_Title is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnLog_TitleChanging(string value);
        /// <summary>Called after Log_Title has Changed.</summary>
        partial void OnLog_TitleChanged();
        /// <summary>Called when Log_Content is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnLog_ContentChanging(string value);
        /// <summary>Called after Log_Content has Changed.</summary>
        partial void OnLog_ContentChanged();
        /// <summary>Called when Log_CreateTime is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnLog_CreateTimeChanging(System.DateTime value);
        /// <summary>Called after Log_CreateTime has Changed.</summary>
        partial void OnLog_CreateTimeChanged();
        /// <summary>Called when Log_ViewCount is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnLog_ViewCountChanging(Nullable<int> value);
        /// <summary>Called after Log_ViewCount has Changed.</summary>
        partial void OnLog_ViewCountChanged();
        /// <summary>Called when Log_CommentCount is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnLog_CommentCountChanging(Nullable<int> value);
        /// <summary>Called after Log_CommentCount has Changed.</summary>
        partial void OnLog_CommentCountChanged();
        /// <summary>Called when Log_RecommendCount is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnLog_RecommendCountChanging(Nullable<int> value);
        /// <summary>Called after Log_RecommendCount has Changed.</summary>
        partial void OnLog_RecommendCountChanged();
        /// <summary>Called when Log_IsVisible is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnLog_IsVisibleChanging(Nullable<bool> value);
        /// <summary>Called after Log_IsVisible has Changed.</summary>
        partial void OnLog_IsVisibleChanged();
        /// <summary>Called when User_FIID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_FIIDChanging(int value);
        /// <summary>Called after User_FIID has Changed.</summary>
        partial void OnUser_FIIDChanged();
        /// <summary>Called when User_DomainName is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_DomainNameChanging(string value);
        /// <summary>Called after User_DomainName has Changed.</summary>
        partial void OnUser_DomainNameChanged();
        /// <summary>Called when Log_IsPasssword is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnLog_IsPassswordChanging(Nullable<bool> value);
        /// <summary>Called after Log_IsPasssword has Changed.</summary>
        partial void OnLog_IsPassswordChanged();
        /// <summary>Called when Log_IsDraft is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnLog_IsDraftChanging(Nullable<bool> value);
        /// <summary>Called after Log_IsDraft has Changed.</summary>
        partial void OnLog_IsDraftChanged();
        /// <summary>Called when Recommend_ThemeId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnRecommend_ThemeIdChanging(Nullable<int> value);
        /// <summary>Called after Recommend_ThemeId has Changed.</summary>
        partial void OnRecommend_ThemeIdChanged();
        #endregion
        
    }
}

