
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace Ncuhome.Blog.Entity
{
    /// <summary>
    /// The class representing the dbo.View_BlogUserFriend table.
    /// </summary>
    [Table(Name="dbo.View_BlogUserFriend")]
    public partial class View_BlogUserFriend
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="View_BlogUserFriend"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public View_BlogUserFriend()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private int _User_Id;

        /// <summary>
        /// Gets or sets the User_Id column value.
        /// </summary>
        [Column(Name="User_Id", Storage="_User_Id", DbType="Int NOT NULL", CanBeNull=false)]
        public int User_Id
        {
            get { return _User_Id; }
            set
            {
                if (_User_Id != value)
                {
                    OnUser_IdChanging(value);
                    _User_Id = value;
                    OnUser_IdChanged();
                }
            }
        }
        
        private int _Frd_UserId;

        /// <summary>
        /// Gets or sets the Frd_UserId column value.
        /// </summary>
        [Column(Name="Frd_UserId", Storage="_Frd_UserId", DbType="Int NOT NULL", CanBeNull=false)]
        public int Frd_UserId
        {
            get { return _Frd_UserId; }
            set
            {
                if (_Frd_UserId != value)
                {
                    OnFrd_UserIdChanging(value);
                    _Frd_UserId = value;
                    OnFrd_UserIdChanged();
                }
            }
        }
        
        private System.DateTime _Frd_CreateTime;

        /// <summary>
        /// Gets or sets the Frd_CreateTime column value.
        /// </summary>
        [Column(Name="Frd_CreateTime", Storage="_Frd_CreateTime", DbType="DateTime NOT NULL", CanBeNull=false)]
        public System.DateTime Frd_CreateTime
        {
            get { return _Frd_CreateTime; }
            set
            {
                if (_Frd_CreateTime != value)
                {
                    OnFrd_CreateTimeChanging(value);
                    _Frd_CreateTime = value;
                    OnFrd_CreateTimeChanged();
                }
            }
        }
        
        private int _Frd_TxzUID;

        /// <summary>
        /// Gets or sets the Frd_TxzUID column value.
        /// </summary>
        [Column(Name="Frd_TxzUID", Storage="_Frd_TxzUID", DbType="Int NOT NULL", CanBeNull=false)]
        public int Frd_TxzUID
        {
            get { return _Frd_TxzUID; }
            set
            {
                if (_Frd_TxzUID != value)
                {
                    OnFrd_TxzUIDChanging(value);
                    _Frd_TxzUID = value;
                    OnFrd_TxzUIDChanged();
                }
            }
        }
        
        private int _Frd_Id;

        /// <summary>
        /// Gets or sets the Frd_Id column value.
        /// </summary>
        [Column(Name="Frd_Id", Storage="_Frd_Id", DbType="Int NOT NULL", CanBeNull=false)]
        public int Frd_Id
        {
            get { return _Frd_Id; }
            set
            {
                if (_Frd_Id != value)
                {
                    OnFrd_IdChanging(value);
                    _Frd_Id = value;
                    OnFrd_IdChanged();
                }
            }
        }
        
        private string _User_NickName;

        /// <summary>
        /// Gets or sets the User_NickName column value.
        /// </summary>
        [Column(Name="User_NickName", Storage="_User_NickName", DbType="NVarChar(50)")]
        public string User_NickName
        {
            get { return _User_NickName; }
            set
            {
                if (_User_NickName != value)
                {
                    OnUser_NickNameChanging(value);
                    _User_NickName = value;
                    OnUser_NickNameChanged();
                }
            }
        }
        
        private string _User_Name;

        /// <summary>
        /// Gets or sets the User_Name column value.
        /// </summary>
        [Column(Name="User_Name", Storage="_User_Name", DbType="NVarChar(50)")]
        public string User_Name
        {
            get { return _User_Name; }
            set
            {
                if (_User_Name != value)
                {
                    OnUser_NameChanging(value);
                    _User_Name = value;
                    OnUser_NameChanged();
                }
            }
        }
        
        private string _User_DomainName;

        /// <summary>
        /// Gets or sets the User_DomainName column value.
        /// </summary>
        [Column(Name="User_DomainName", Storage="_User_DomainName", DbType="NVarChar(20)")]
        public string User_DomainName
        {
            get { return _User_DomainName; }
            set
            {
                if (_User_DomainName != value)
                {
                    OnUser_DomainNameChanging(value);
                    _User_DomainName = value;
                    OnUser_DomainNameChanged();
                }
            }
        }
        
        private string _User_PortraitUrl;

        /// <summary>
        /// Gets or sets the User_PortraitUrl column value.
        /// </summary>
        [Column(Name="User_PortraitUrl", Storage="_User_PortraitUrl", DbType="NVarChar(50)")]
        public string User_PortraitUrl
        {
            get { return _User_PortraitUrl; }
            set
            {
                if (_User_PortraitUrl != value)
                {
                    OnUser_PortraitUrlChanging(value);
                    _User_PortraitUrl = value;
                    OnUser_PortraitUrlChanged();
                }
            }
        }
        
        private Nullable<int> _User_FIID;

        /// <summary>
        /// Gets or sets the User_FIID column value.
        /// </summary>
        [Column(Name="User_FIID", Storage="_User_FIID", DbType="Int")]
        public Nullable<int> User_FIID
        {
            get { return _User_FIID; }
            set
            {
                if (_User_FIID != value)
                {
                    OnUser_FIIDChanging(value);
                    _User_FIID = value;
                    OnUser_FIIDChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when User_Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_IdChanging(int value);
        /// <summary>Called after User_Id has Changed.</summary>
        partial void OnUser_IdChanged();
        /// <summary>Called when Frd_UserId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFrd_UserIdChanging(int value);
        /// <summary>Called after Frd_UserId has Changed.</summary>
        partial void OnFrd_UserIdChanged();
        /// <summary>Called when Frd_CreateTime is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFrd_CreateTimeChanging(System.DateTime value);
        /// <summary>Called after Frd_CreateTime has Changed.</summary>
        partial void OnFrd_CreateTimeChanged();
        /// <summary>Called when Frd_TxzUID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFrd_TxzUIDChanging(int value);
        /// <summary>Called after Frd_TxzUID has Changed.</summary>
        partial void OnFrd_TxzUIDChanged();
        /// <summary>Called when Frd_Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFrd_IdChanging(int value);
        /// <summary>Called after Frd_Id has Changed.</summary>
        partial void OnFrd_IdChanged();
        /// <summary>Called when User_NickName is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_NickNameChanging(string value);
        /// <summary>Called after User_NickName has Changed.</summary>
        partial void OnUser_NickNameChanged();
        /// <summary>Called when User_Name is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_NameChanging(string value);
        /// <summary>Called after User_Name has Changed.</summary>
        partial void OnUser_NameChanged();
        /// <summary>Called when User_DomainName is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_DomainNameChanging(string value);
        /// <summary>Called after User_DomainName has Changed.</summary>
        partial void OnUser_DomainNameChanged();
        /// <summary>Called when User_PortraitUrl is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_PortraitUrlChanging(string value);
        /// <summary>Called after User_PortraitUrl has Changed.</summary>
        partial void OnUser_PortraitUrlChanged();
        /// <summary>Called when User_FIID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_FIIDChanging(Nullable<int> value);
        /// <summary>Called after User_FIID has Changed.</summary>
        partial void OnUser_FIIDChanged();
        #endregion
        
    }
}

