
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace Ncuhome.Blog.Entity
{
    /// <summary>
    /// The class representing the dbo.View_WeblogThemeCssFile table.
    /// </summary>
    [Table(Name="dbo.View_WeblogThemeCssFile")]
    public partial class View_WeblogThemeCssFile
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="View_WeblogThemeCssFile"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public View_WeblogThemeCssFile()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private int _Theme_Id;

        /// <summary>
        /// Gets or sets the Theme_Id column value.
        /// </summary>
        [Column(Name="Theme_Id", Storage="_Theme_Id", DbType="Int NOT NULL", CanBeNull=false)]
        public int Theme_Id
        {
            get { return _Theme_Id; }
            set
            {
                if (_Theme_Id != value)
                {
                    OnTheme_IdChanging(value);
                    _Theme_Id = value;
                    OnTheme_IdChanged();
                }
            }
        }
        
        private int _CssFile_Id;

        /// <summary>
        /// Gets or sets the CssFile_Id column value.
        /// </summary>
        [Column(Name="CssFile_Id", Storage="_CssFile_Id", DbType="Int NOT NULL", CanBeNull=false)]
        public int CssFile_Id
        {
            get { return _CssFile_Id; }
            set
            {
                if (_CssFile_Id != value)
                {
                    OnCssFile_IdChanging(value);
                    _CssFile_Id = value;
                    OnCssFile_IdChanged();
                }
            }
        }
        
        private string _CssFile_Intro;

        /// <summary>
        /// Gets or sets the CssFile_Intro column value.
        /// </summary>
        [Column(Name="CssFile_Intro", Storage="_CssFile_Intro", DbType="NChar(500)")]
        public string CssFile_Intro
        {
            get { return _CssFile_Intro; }
            set
            {
                if (_CssFile_Intro != value)
                {
                    OnCssFile_IntroChanging(value);
                    _CssFile_Intro = value;
                    OnCssFile_IntroChanged();
                }
            }
        }
        
        private string _CssFile_Name;

        /// <summary>
        /// Gets or sets the CssFile_Name column value.
        /// </summary>
        [Column(Name="CssFile_Name", Storage="_CssFile_Name", DbType="NChar(50)")]
        public string CssFile_Name
        {
            get { return _CssFile_Name; }
            set
            {
                if (_CssFile_Name != value)
                {
                    OnCssFile_NameChanging(value);
                    _CssFile_Name = value;
                    OnCssFile_NameChanged();
                }
            }
        }
        
        private Nullable<System.DateTime> _CssFile_CreateTile;

        /// <summary>
        /// Gets or sets the CssFile_CreateTile column value.
        /// </summary>
        [Column(Name="CssFile_CreateTile", Storage="_CssFile_CreateTile", DbType="DateTime")]
        public Nullable<System.DateTime> CssFile_CreateTile
        {
            get { return _CssFile_CreateTile; }
            set
            {
                if (_CssFile_CreateTile != value)
                {
                    OnCssFile_CreateTileChanging(value);
                    _CssFile_CreateTile = value;
                    OnCssFile_CreateTileChanged();
                }
            }
        }
        
        private string _CssFile_Path;

        /// <summary>
        /// Gets or sets the CssFile_Path column value.
        /// </summary>
        [Column(Name="CssFile_Path", Storage="_CssFile_Path", DbType="NChar(200)")]
        public string CssFile_Path
        {
            get { return _CssFile_Path; }
            set
            {
                if (_CssFile_Path != value)
                {
                    OnCssFile_PathChanging(value);
                    _CssFile_Path = value;
                    OnCssFile_PathChanged();
                }
            }
        }
        
        private Nullable<int> _CssFile_CreateUserId;

        /// <summary>
        /// Gets or sets the CssFile_CreateUserId column value.
        /// </summary>
        [Column(Name="CssFile_CreateUserId", Storage="_CssFile_CreateUserId", DbType="Int")]
        public Nullable<int> CssFile_CreateUserId
        {
            get { return _CssFile_CreateUserId; }
            set
            {
                if (_CssFile_CreateUserId != value)
                {
                    OnCssFile_CreateUserIdChanging(value);
                    _CssFile_CreateUserId = value;
                    OnCssFile_CreateUserIdChanged();
                }
            }
        }
        
        private string _Theme_Name;

        /// <summary>
        /// Gets or sets the Theme_Name column value.
        /// </summary>
        [Column(Name="Theme_Name", Storage="_Theme_Name", DbType="NChar(50)")]
        public string Theme_Name
        {
            get { return _Theme_Name; }
            set
            {
                if (_Theme_Name != value)
                {
                    OnTheme_NameChanging(value);
                    _Theme_Name = value;
                    OnTheme_NameChanged();
                }
            }
        }
        
        private string _Theme_Intro;

        /// <summary>
        /// Gets or sets the Theme_Intro column value.
        /// </summary>
        [Column(Name="Theme_Intro", Storage="_Theme_Intro", DbType="NChar(500)")]
        public string Theme_Intro
        {
            get { return _Theme_Intro; }
            set
            {
                if (_Theme_Intro != value)
                {
                    OnTheme_IntroChanging(value);
                    _Theme_Intro = value;
                    OnTheme_IntroChanged();
                }
            }
        }
        
        private string _CssFile_IndexPicPath;

        /// <summary>
        /// Gets or sets the CssFile_IndexPicPath column value.
        /// </summary>
        [Column(Name="CssFile_IndexPicPath", Storage="_CssFile_IndexPicPath", DbType="NChar(200)")]
        public string CssFile_IndexPicPath
        {
            get { return _CssFile_IndexPicPath; }
            set
            {
                if (_CssFile_IndexPicPath != value)
                {
                    OnCssFile_IndexPicPathChanging(value);
                    _CssFile_IndexPicPath = value;
                    OnCssFile_IndexPicPathChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when Theme_Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTheme_IdChanging(int value);
        /// <summary>Called after Theme_Id has Changed.</summary>
        partial void OnTheme_IdChanged();
        /// <summary>Called when CssFile_Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnCssFile_IdChanging(int value);
        /// <summary>Called after CssFile_Id has Changed.</summary>
        partial void OnCssFile_IdChanged();
        /// <summary>Called when CssFile_Intro is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnCssFile_IntroChanging(string value);
        /// <summary>Called after CssFile_Intro has Changed.</summary>
        partial void OnCssFile_IntroChanged();
        /// <summary>Called when CssFile_Name is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnCssFile_NameChanging(string value);
        /// <summary>Called after CssFile_Name has Changed.</summary>
        partial void OnCssFile_NameChanged();
        /// <summary>Called when CssFile_CreateTile is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnCssFile_CreateTileChanging(Nullable<System.DateTime> value);
        /// <summary>Called after CssFile_CreateTile has Changed.</summary>
        partial void OnCssFile_CreateTileChanged();
        /// <summary>Called when CssFile_Path is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnCssFile_PathChanging(string value);
        /// <summary>Called after CssFile_Path has Changed.</summary>
        partial void OnCssFile_PathChanged();
        /// <summary>Called when CssFile_CreateUserId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnCssFile_CreateUserIdChanging(Nullable<int> value);
        /// <summary>Called after CssFile_CreateUserId has Changed.</summary>
        partial void OnCssFile_CreateUserIdChanged();
        /// <summary>Called when Theme_Name is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTheme_NameChanging(string value);
        /// <summary>Called after Theme_Name has Changed.</summary>
        partial void OnTheme_NameChanged();
        /// <summary>Called when Theme_Intro is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTheme_IntroChanging(string value);
        /// <summary>Called after Theme_Intro has Changed.</summary>
        partial void OnTheme_IntroChanged();
        /// <summary>Called when CssFile_IndexPicPath is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnCssFile_IndexPicPathChanging(string value);
        /// <summary>Called after CssFile_IndexPicPath has Changed.</summary>
        partial void OnCssFile_IndexPicPathChanged();
        #endregion
        
    }
}

