
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace Ncuhome.Blog.Entity
{
    /// <summary>
    /// The class representing the dbo.View_WeblogUserComment table.
    /// </summary>
    [Table(Name="dbo.View_WeblogUserComment")]
    public partial class View_WeblogUserComment
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="View_WeblogUserComment"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public View_WeblogUserComment()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private string _User_NickName;

        /// <summary>
        /// Gets or sets the User_NickName column value.
        /// </summary>
        [Column(Name="User_NickName", Storage="_User_NickName", DbType="NVarChar(50)")]
        public string User_NickName
        {
            get { return _User_NickName; }
            set
            {
                if (_User_NickName != value)
                {
                    OnUser_NickNameChanging(value);
                    _User_NickName = value;
                    OnUser_NickNameChanged();
                }
            }
        }
        
        private string _User_PortraitUrl;

        /// <summary>
        /// Gets or sets the User_PortraitUrl column value.
        /// </summary>
        [Column(Name="User_PortraitUrl", Storage="_User_PortraitUrl", DbType="NVarChar(50)")]
        public string User_PortraitUrl
        {
            get { return _User_PortraitUrl; }
            set
            {
                if (_User_PortraitUrl != value)
                {
                    OnUser_PortraitUrlChanging(value);
                    _User_PortraitUrl = value;
                    OnUser_PortraitUrlChanged();
                }
            }
        }
        
        private Nullable<int> _User_FIID;

        /// <summary>
        /// Gets or sets the User_FIID column value.
        /// </summary>
        [Column(Name="User_FIID", Storage="_User_FIID", DbType="Int")]
        public Nullable<int> User_FIID
        {
            get { return _User_FIID; }
            set
            {
                if (_User_FIID != value)
                {
                    OnUser_FIIDChanging(value);
                    _User_FIID = value;
                    OnUser_FIIDChanged();
                }
            }
        }
        
        private string _User_DomainName;

        /// <summary>
        /// Gets or sets the User_DomainName column value.
        /// </summary>
        [Column(Name="User_DomainName", Storage="_User_DomainName", DbType="NVarChar(20)")]
        public string User_DomainName
        {
            get { return _User_DomainName; }
            set
            {
                if (_User_DomainName != value)
                {
                    OnUser_DomainNameChanging(value);
                    _User_DomainName = value;
                    OnUser_DomainNameChanged();
                }
            }
        }
        
        private string _User_Movie;

        /// <summary>
        /// Gets or sets the User_Movie column value.
        /// </summary>
        [Column(Name="User_Movie", Storage="_User_Movie", DbType="NVarChar(100)")]
        public string User_Movie
        {
            get { return _User_Movie; }
            set
            {
                if (_User_Movie != value)
                {
                    OnUser_MovieChanging(value);
                    _User_Movie = value;
                    OnUser_MovieChanged();
                }
            }
        }
        
        private string _User_Music;

        /// <summary>
        /// Gets or sets the User_Music column value.
        /// </summary>
        [Column(Name="User_Music", Storage="_User_Music", DbType="NVarChar(100)")]
        public string User_Music
        {
            get { return _User_Music; }
            set
            {
                if (_User_Music != value)
                {
                    OnUser_MusicChanging(value);
                    _User_Music = value;
                    OnUser_MusicChanged();
                }
            }
        }
        
        private string _User_Book;

        /// <summary>
        /// Gets or sets the User_Book column value.
        /// </summary>
        [Column(Name="User_Book", Storage="_User_Book", DbType="NVarChar(100)")]
        public string User_Book
        {
            get { return _User_Book; }
            set
            {
                if (_User_Book != value)
                {
                    OnUser_BookChanging(value);
                    _User_Book = value;
                    OnUser_BookChanged();
                }
            }
        }
        
        private string _User_Interest;

        /// <summary>
        /// Gets or sets the User_Interest column value.
        /// </summary>
        [Column(Name="User_Interest", Storage="_User_Interest", DbType="NVarChar(100)")]
        public string User_Interest
        {
            get { return _User_Interest; }
            set
            {
                if (_User_Interest != value)
                {
                    OnUser_InterestChanging(value);
                    _User_Interest = value;
                    OnUser_InterestChanged();
                }
            }
        }
        
        private string _User_HomePage;

        /// <summary>
        /// Gets or sets the User_HomePage column value.
        /// </summary>
        [Column(Name="User_HomePage", Storage="_User_HomePage", DbType="NVarChar(250)")]
        public string User_HomePage
        {
            get { return _User_HomePage; }
            set
            {
                if (_User_HomePage != value)
                {
                    OnUser_HomePageChanging(value);
                    _User_HomePage = value;
                    OnUser_HomePageChanged();
                }
            }
        }
        
        private string _User_QQ;

        /// <summary>
        /// Gets or sets the User_QQ column value.
        /// </summary>
        [Column(Name="User_QQ", Storage="_User_QQ", DbType="NVarChar(50)")]
        public string User_QQ
        {
            get { return _User_QQ; }
            set
            {
                if (_User_QQ != value)
                {
                    OnUser_QQChanging(value);
                    _User_QQ = value;
                    OnUser_QQChanged();
                }
            }
        }
        
        private string _User_MSN;

        /// <summary>
        /// Gets or sets the User_MSN column value.
        /// </summary>
        [Column(Name="User_MSN", Storage="_User_MSN", DbType="NVarChar(50)")]
        public string User_MSN
        {
            get { return _User_MSN; }
            set
            {
                if (_User_MSN != value)
                {
                    OnUser_MSNChanging(value);
                    _User_MSN = value;
                    OnUser_MSNChanged();
                }
            }
        }
        
        private Nullable<int> _Comment_LogId;

        /// <summary>
        /// Gets or sets the Comment_LogId column value.
        /// </summary>
        [Column(Name="Comment_LogId", Storage="_Comment_LogId", DbType="Int")]
        public Nullable<int> Comment_LogId
        {
            get { return _Comment_LogId; }
            set
            {
                if (_Comment_LogId != value)
                {
                    OnComment_LogIdChanging(value);
                    _Comment_LogId = value;
                    OnComment_LogIdChanged();
                }
            }
        }
        
        private string _Comment_Content;

        /// <summary>
        /// Gets or sets the Comment_Content column value.
        /// </summary>
        [Column(Name="Comment_Content", Storage="_Comment_Content", DbType="NVarChar(MAX)")]
        public string Comment_Content
        {
            get { return _Comment_Content; }
            set
            {
                if (_Comment_Content != value)
                {
                    OnComment_ContentChanging(value);
                    _Comment_Content = value;
                    OnComment_ContentChanged();
                }
            }
        }
        
        private Nullable<int> _Comment_ToCommentId;

        /// <summary>
        /// Gets or sets the Comment_ToCommentId column value.
        /// </summary>
        [Column(Name="Comment_ToCommentId", Storage="_Comment_ToCommentId", DbType="Int")]
        public Nullable<int> Comment_ToCommentId
        {
            get { return _Comment_ToCommentId; }
            set
            {
                if (_Comment_ToCommentId != value)
                {
                    OnComment_ToCommentIdChanging(value);
                    _Comment_ToCommentId = value;
                    OnComment_ToCommentIdChanged();
                }
            }
        }
        
        private Nullable<System.DateTime> _Comment_CreateTime;

        /// <summary>
        /// Gets or sets the Comment_CreateTime column value.
        /// </summary>
        [Column(Name="Comment_CreateTime", Storage="_Comment_CreateTime", DbType="DateTime")]
        public Nullable<System.DateTime> Comment_CreateTime
        {
            get { return _Comment_CreateTime; }
            set
            {
                if (_Comment_CreateTime != value)
                {
                    OnComment_CreateTimeChanging(value);
                    _Comment_CreateTime = value;
                    OnComment_CreateTimeChanged();
                }
            }
        }
        
        private Nullable<System.DateTime> _Comment_LastModiTime;

        /// <summary>
        /// Gets or sets the Comment_LastModiTime column value.
        /// </summary>
        [Column(Name="Comment_LastModiTime", Storage="_Comment_LastModiTime", DbType="DateTime")]
        public Nullable<System.DateTime> Comment_LastModiTime
        {
            get { return _Comment_LastModiTime; }
            set
            {
                if (_Comment_LastModiTime != value)
                {
                    OnComment_LastModiTimeChanging(value);
                    _Comment_LastModiTime = value;
                    OnComment_LastModiTimeChanged();
                }
            }
        }
        
        private string _Comment_GuestName;

        /// <summary>
        /// Gets or sets the Comment_GuestName column value.
        /// </summary>
        [Column(Name="Comment_GuestName", Storage="_Comment_GuestName", DbType="NVarChar(20)")]
        public string Comment_GuestName
        {
            get { return _Comment_GuestName; }
            set
            {
                if (_Comment_GuestName != value)
                {
                    OnComment_GuestNameChanging(value);
                    _Comment_GuestName = value;
                    OnComment_GuestNameChanged();
                }
            }
        }
        
        private Nullable<int> _Comment_UserId;

        /// <summary>
        /// Gets or sets the Comment_UserId column value.
        /// </summary>
        [Column(Name="Comment_UserId", Storage="_Comment_UserId", DbType="Int")]
        public Nullable<int> Comment_UserId
        {
            get { return _Comment_UserId; }
            set
            {
                if (_Comment_UserId != value)
                {
                    OnComment_UserIdChanging(value);
                    _Comment_UserId = value;
                    OnComment_UserIdChanged();
                }
            }
        }
        
        private int _Comment_Id;

        /// <summary>
        /// Gets or sets the Comment_Id column value.
        /// </summary>
        [Column(Name="Comment_Id", Storage="_Comment_Id", DbType="Int NOT NULL", CanBeNull=false)]
        public int Comment_Id
        {
            get { return _Comment_Id; }
            set
            {
                if (_Comment_Id != value)
                {
                    OnComment_IdChanging(value);
                    _Comment_Id = value;
                    OnComment_IdChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when User_NickName is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_NickNameChanging(string value);
        /// <summary>Called after User_NickName has Changed.</summary>
        partial void OnUser_NickNameChanged();
        /// <summary>Called when User_PortraitUrl is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_PortraitUrlChanging(string value);
        /// <summary>Called after User_PortraitUrl has Changed.</summary>
        partial void OnUser_PortraitUrlChanged();
        /// <summary>Called when User_FIID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_FIIDChanging(Nullable<int> value);
        /// <summary>Called after User_FIID has Changed.</summary>
        partial void OnUser_FIIDChanged();
        /// <summary>Called when User_DomainName is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_DomainNameChanging(string value);
        /// <summary>Called after User_DomainName has Changed.</summary>
        partial void OnUser_DomainNameChanged();
        /// <summary>Called when User_Movie is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_MovieChanging(string value);
        /// <summary>Called after User_Movie has Changed.</summary>
        partial void OnUser_MovieChanged();
        /// <summary>Called when User_Music is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_MusicChanging(string value);
        /// <summary>Called after User_Music has Changed.</summary>
        partial void OnUser_MusicChanged();
        /// <summary>Called when User_Book is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_BookChanging(string value);
        /// <summary>Called after User_Book has Changed.</summary>
        partial void OnUser_BookChanged();
        /// <summary>Called when User_Interest is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_InterestChanging(string value);
        /// <summary>Called after User_Interest has Changed.</summary>
        partial void OnUser_InterestChanged();
        /// <summary>Called when User_HomePage is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_HomePageChanging(string value);
        /// <summary>Called after User_HomePage has Changed.</summary>
        partial void OnUser_HomePageChanged();
        /// <summary>Called when User_QQ is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_QQChanging(string value);
        /// <summary>Called after User_QQ has Changed.</summary>
        partial void OnUser_QQChanged();
        /// <summary>Called when User_MSN is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUser_MSNChanging(string value);
        /// <summary>Called after User_MSN has Changed.</summary>
        partial void OnUser_MSNChanged();
        /// <summary>Called when Comment_LogId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnComment_LogIdChanging(Nullable<int> value);
        /// <summary>Called after Comment_LogId has Changed.</summary>
        partial void OnComment_LogIdChanged();
        /// <summary>Called when Comment_Content is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnComment_ContentChanging(string value);
        /// <summary>Called after Comment_Content has Changed.</summary>
        partial void OnComment_ContentChanged();
        /// <summary>Called when Comment_ToCommentId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnComment_ToCommentIdChanging(Nullable<int> value);
        /// <summary>Called after Comment_ToCommentId has Changed.</summary>
        partial void OnComment_ToCommentIdChanged();
        /// <summary>Called when Comment_CreateTime is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnComment_CreateTimeChanging(Nullable<System.DateTime> value);
        /// <summary>Called after Comment_CreateTime has Changed.</summary>
        partial void OnComment_CreateTimeChanged();
        /// <summary>Called when Comment_LastModiTime is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnComment_LastModiTimeChanging(Nullable<System.DateTime> value);
        /// <summary>Called after Comment_LastModiTime has Changed.</summary>
        partial void OnComment_LastModiTimeChanged();
        /// <summary>Called when Comment_GuestName is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnComment_GuestNameChanging(string value);
        /// <summary>Called after Comment_GuestName has Changed.</summary>
        partial void OnComment_GuestNameChanged();
        /// <summary>Called when Comment_UserId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnComment_UserIdChanging(Nullable<int> value);
        /// <summary>Called after Comment_UserId has Changed.</summary>
        partial void OnComment_UserIdChanged();
        /// <summary>Called when Comment_Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnComment_IdChanging(int value);
        /// <summary>Called after Comment_Id has Changed.</summary>
        partial void OnComment_IdChanged();
        #endregion
        
    }
}

