
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace Ncuhome.Blog.Entity 
{
    /// <summary>
    /// The class representing the dbo.Weblog_GroupClass table.
    /// </summary>
    [Table(Name="dbo.Weblog_GroupClass")]
    public partial class Weblog_GroupClass
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Weblog_GroupClass"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public Weblog_GroupClass()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private int _GroupClass_Id = default(int);

        /// <summary>
        /// Gets the GroupClass_Id column value.
        /// </summary>
        [Column(Name="GroupClass_Id", Storage="_GroupClass_Id", DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, CanBeNull=false)]
        public int GroupClass_Id
        {
            get { return _GroupClass_Id; }
            set
            {
                if (_GroupClass_Id != value)
                {
                    OnGroupClass_IdChanging(value);
                    _GroupClass_Id = value;
                    OnGroupClass_IdChanged();
                }
            }
        }
        
        private string _GroupClass_Name;

        /// <summary>
        /// Gets or sets the GroupClass_Name column value.
        /// </summary>
        [Column(Name="GroupClass_Name", Storage="_GroupClass_Name", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
        public string GroupClass_Name
        {
            get { return _GroupClass_Name; }
            set
            {
                if (_GroupClass_Name != value)
                {
                    OnGroupClass_NameChanging(value);
                    _GroupClass_Name = value;
                    OnGroupClass_NameChanged();
                }
            }
        }
        
        private Nullable<int> _GroupClass_GroupCount;

        /// <summary>
        /// Gets or sets the GroupClass_GroupCount column value.
        /// </summary>
        [Column(Name="GroupClass_GroupCount", Storage="_GroupClass_GroupCount", DbType="Int")]
        public Nullable<int> GroupClass_GroupCount
        {
            get { return _GroupClass_GroupCount; }
            set
            {
                if (_GroupClass_GroupCount != value)
                {
                    OnGroupClass_GroupCountChanging(value);
                    _GroupClass_GroupCount = value;
                    OnGroupClass_GroupCountChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when GroupClass_Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnGroupClass_IdChanging(int value);
        /// <summary>Called after GroupClass_Id has Changed.</summary>
        partial void OnGroupClass_IdChanged();
        /// <summary>Called when GroupClass_Name is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnGroupClass_NameChanging(string value);
        /// <summary>Called after GroupClass_Name has Changed.</summary>
        partial void OnGroupClass_NameChanged();
        /// <summary>Called when GroupClass_GroupCount is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnGroupClass_GroupCountChanging(Nullable<int> value);
        /// <summary>Called after GroupClass_GroupCount has Changed.</summary>
        partial void OnGroupClass_GroupCountChanged();
        #endregion
        
    }
}

