
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace Ncuhome.Blog.Entity 
{
    /// <summary>
    /// The class representing the dbo.Weblog_FreshContent table.
    /// </summary>
    [Table(Name="dbo.Weblog_FreshContent")]
    public partial class Weblog_FreshContent
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Weblog_FreshContent"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public Weblog_FreshContent()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private int _FC_Id = default(int);

        /// <summary>
        /// Gets the FC_Id column value.
        /// </summary>
        [Column(Name="FC_Id", Storage="_FC_Id", DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, CanBeNull=false)]
        public int FC_Id
        {
            get { return _FC_Id; }
            set
            {
                if (_FC_Id != value)
                {
                    OnFC_IdChanging(value);
                    _FC_Id = value;
                    OnFC_IdChanged();
                }
            }
        }
        
        private int _FC_FDId;

        /// <summary>
        /// Gets or sets the FC_FDId column value.
        /// </summary>
        [Column(Name="FC_FDId", Storage="_FC_FDId", DbType="Int NOT NULL", CanBeNull=false)]
        public int FC_FDId
        {
            get { return _FC_FDId; }
            set
            {
                if (_FC_FDId != value)
                {
                    OnFC_FDIdChanging(value);
                    _FC_FDId = value;
                    OnFC_FDIdChanged();
                }
            }
        }
        
        private int _FC_UserId;

        /// <summary>
        /// Gets or sets the FC_UserId column value.
        /// </summary>
        [Column(Name="FC_UserId", Storage="_FC_UserId", DbType="Int NOT NULL", CanBeNull=false)]
        public int FC_UserId
        {
            get { return _FC_UserId; }
            set
            {
                if (_FC_UserId != value)
                {
                    OnFC_UserIdChanging(value);
                    _FC_UserId = value;
                    OnFC_UserIdChanged();
                }
            }
        }
        
        private string _FC_Title;

        /// <summary>
        /// Gets or sets the FC_Title column value.
        /// </summary>
        [Column(Name="FC_Title", Storage="_FC_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
        public string FC_Title
        {
            get { return _FC_Title; }
            set
            {
                if (_FC_Title != value)
                {
                    OnFC_TitleChanging(value);
                    _FC_Title = value;
                    OnFC_TitleChanged();
                }
            }
        }
        
        private string _FC_Url;

        /// <summary>
        /// Gets or sets the FC_Url column value.
        /// </summary>
        [Column(Name="FC_Url", Storage="_FC_Url", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
        public string FC_Url
        {
            get { return _FC_Url; }
            set
            {
                if (_FC_Url != value)
                {
                    OnFC_UrlChanging(value);
                    _FC_Url = value;
                    OnFC_UrlChanged();
                }
            }
        }
        
        private int _FC_TypeId;

        /// <summary>
        /// Gets or sets the FC_TypeId column value.
        /// </summary>
        [Column(Name="FC_TypeId", Storage="_FC_TypeId", DbType="Int NOT NULL", CanBeNull=false)]
        public int FC_TypeId
        {
            get { return _FC_TypeId; }
            set
            {
                if (_FC_TypeId != value)
                {
                    OnFC_TypeIdChanging(value);
                    _FC_TypeId = value;
                    OnFC_TypeIdChanged();
                }
            }
        }
        
        private int _FC_FromUserId;

        /// <summary>
        /// Gets or sets the FC_FromUserId column value.
        /// </summary>
        [Column(Name="FC_FromUserId", Storage="_FC_FromUserId", DbType="Int NOT NULL", CanBeNull=false)]
        public int FC_FromUserId
        {
            get { return _FC_FromUserId; }
            set
            {
                if (_FC_FromUserId != value)
                {
                    OnFC_FromUserIdChanging(value);
                    _FC_FromUserId = value;
                    OnFC_FromUserIdChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when FC_Id is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFC_IdChanging(int value);
        /// <summary>Called after FC_Id has Changed.</summary>
        partial void OnFC_IdChanged();
        /// <summary>Called when FC_FDId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFC_FDIdChanging(int value);
        /// <summary>Called after FC_FDId has Changed.</summary>
        partial void OnFC_FDIdChanged();
        /// <summary>Called when FC_UserId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFC_UserIdChanging(int value);
        /// <summary>Called after FC_UserId has Changed.</summary>
        partial void OnFC_UserIdChanged();
        /// <summary>Called when FC_Title is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFC_TitleChanging(string value);
        /// <summary>Called after FC_Title has Changed.</summary>
        partial void OnFC_TitleChanged();
        /// <summary>Called when FC_Url is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFC_UrlChanging(string value);
        /// <summary>Called after FC_Url has Changed.</summary>
        partial void OnFC_UrlChanged();
        /// <summary>Called when FC_TypeId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFC_TypeIdChanging(int value);
        /// <summary>Called after FC_TypeId has Changed.</summary>
        partial void OnFC_TypeIdChanged();
        /// <summary>Called when FC_FromUserId is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnFC_FromUserIdChanging(int value);
        /// <summary>Called after FC_FromUserId has Changed.</summary>
        partial void OnFC_FromUserIdChanged();
        #endregion
        
    }
}

