
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace Ncuhome.Blog.Entity
{
    /// <summary>
    /// The class representing the dbo.Weblog_RecommendTheme table.
    /// </summary>
    [Table(Name="dbo.Weblog_RecommendTheme")]
    public partial class Weblog_RecommendTheme
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Weblog_RecommendTheme"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public Weblog_RecommendTheme()
        {
            OnCreated();
        }
        #endregion
        
        #region Column Mapped Properties
        
        private int _ID = default(int);

        /// <summary>
        /// Gets the ID column value.
        /// </summary>
        [Column(Name="ID", Storage="_ID", DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, CanBeNull=false)]
        public int ID
        {
            get { return _ID; }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    _ID = value;
                    OnIDChanged();
                }
            }
        }
        
        private string _Reco_Title;

        /// <summary>
        /// Gets or sets the Reco_Title column value.
        /// </summary>
        [Column(Name="Reco_Title", Storage="_Reco_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
        public string Reco_Title
        {
            get { return _Reco_Title; }
            set
            {
                if (_Reco_Title != value)
                {
                    OnReco_TitleChanging(value);
                    _Reco_Title = value;
                    OnReco_TitleChanged();
                }
            }
        }
        
        private string _Reco_Content;

        /// <summary>
        /// Gets or sets the Reco_Content column value.
        /// </summary>
        [Column(Name="Reco_Content", Storage="_Reco_Content", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
        public string Reco_Content
        {
            get { return _Reco_Content; }
            set
            {
                if (_Reco_Content != value)
                {
                    OnReco_ContentChanging(value);
                    _Reco_Content = value;
                    OnReco_ContentChanged();
                }
            }
        }
        
        private System.DateTime _Reco_CreateTime;

        /// <summary>
        /// Gets or sets the Reco_CreateTime column value.
        /// </summary>
        [Column(Name="Reco_CreateTime", Storage="_Reco_CreateTime", DbType="DateTime NOT NULL", CanBeNull=false)]
        public System.DateTime Reco_CreateTime
        {
            get { return _Reco_CreateTime; }
            set
            {
                if (_Reco_CreateTime != value)
                {
                    OnReco_CreateTimeChanging(value);
                    _Reco_CreateTime = value;
                    OnReco_CreateTimeChanged();
                }
            }
        }
        
        private Nullable<bool> _Reco_Visible;

        /// <summary>
        /// Gets or sets the Reco_Visible column value.
        /// </summary>
        [Column(Name="Reco_Visible", Storage="_Reco_Visible", DbType="Bit")]
        public Nullable<bool> Reco_Visible
        {
            get { return _Reco_Visible; }
            set
            {
                if (_Reco_Visible != value)
                {
                    OnReco_VisibleChanging(value);
                    _Reco_Visible = value;
                    OnReco_VisibleChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when ID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnIDChanging(int value);
        /// <summary>Called after ID has Changed.</summary>
        partial void OnIDChanged();
        /// <summary>Called when Reco_Title is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnReco_TitleChanging(string value);
        /// <summary>Called after Reco_Title has Changed.</summary>
        partial void OnReco_TitleChanged();
        /// <summary>Called when Reco_Content is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnReco_ContentChanging(string value);
        /// <summary>Called after Reco_Content has Changed.</summary>
        partial void OnReco_ContentChanged();
        /// <summary>Called when Reco_CreateTime is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnReco_CreateTimeChanging(System.DateTime value);
        /// <summary>Called after Reco_CreateTime has Changed.</summary>
        partial void OnReco_CreateTimeChanged();
        /// <summary>Called when Reco_Visible is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnReco_VisibleChanging(Nullable<bool> value);
        /// <summary>Called after Reco_Visible has Changed.</summary>
        partial void OnReco_VisibleChanged();
        #endregion
        
    }
}

