//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1434.
// 
#pragma warning disable 1591

namespace Ncuhome.Blog.Core.GbookReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GbookWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class GbookWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMsgByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRemotIPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMsgByMsgIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMsgByFIIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback HasFIIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback HasMsgIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFIIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGbookOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGbookPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSingleListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GbookWebService() {
            this.Url = global::Ncuhome.Blog.Core.Properties.Settings.Default.Blog_Core_GbookReference_GbookWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddAdminCompletedEventHandler AddAdminCompleted;
        
        /// <remarks/>
        public event IsAdminCompletedEventHandler IsAdminCompleted;
        
        /// <remarks/>
        public event GetMsgByIDCompletedEventHandler GetMsgByIDCompleted;
        
        /// <remarks/>
        public event GetRemotIPCompletedEventHandler GetRemotIPCompleted;
        
        /// <remarks/>
        public event GetLastMsgCompletedEventHandler GetLastMsgCompleted;
        
        /// <remarks/>
        public event InsertMsgCompletedEventHandler InsertMsgCompleted;
        
        /// <remarks/>
        public event DeleteMsgByMsgIDCompletedEventHandler DeleteMsgByMsgIDCompleted;
        
        /// <remarks/>
        public event DeleteMsgByFIIDCompletedEventHandler DeleteMsgByFIIDCompleted;
        
        /// <remarks/>
        public event HasFIIDCompletedEventHandler HasFIIDCompleted;
        
        /// <remarks/>
        public event HasMsgIDCompletedEventHandler HasMsgIDCompleted;
        
        /// <remarks/>
        public event GetFIIDCompletedEventHandler GetFIIDCompleted;
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetGbookCompletedEventHandler GetGbookCompleted;
        
        /// <remarks/>
        public event GetGbookPageCompletedEventHandler GetGbookPageCompleted;
        
        /// <remarks/>
        public event GetAllListCompletedEventHandler GetAllListCompleted;
        
        /// <remarks/>
        public event GetSingleListCompletedEventHandler GetSingleListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddAdmin() {
            object[] results = this.Invoke("AddAdmin", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddAdminAsync() {
            this.AddAdminAsync(null);
        }
        
        /// <remarks/>
        public void AddAdminAsync(object userState) {
            if ((this.AddAdminOperationCompleted == null)) {
                this.AddAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAdminOperationCompleted);
            }
            this.InvokeAsync("AddAdmin", new object[0], this.AddAdminOperationCompleted, userState);
        }
        
        private void OnAddAdminOperationCompleted(object arg) {
            if ((this.AddAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAdminCompleted(this, new AddAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsAdmin(int FIID, int TxzID) {
            object[] results = this.Invoke("IsAdmin", new object[] {
                        FIID,
                        TxzID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsAdminAsync(int FIID, int TxzID) {
            this.IsAdminAsync(FIID, TxzID, null);
        }
        
        /// <remarks/>
        public void IsAdminAsync(int FIID, int TxzID, object userState) {
            if ((this.IsAdminOperationCompleted == null)) {
                this.IsAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsAdminOperationCompleted);
            }
            this.InvokeAsync("IsAdmin", new object[] {
                        FIID,
                        TxzID}, this.IsAdminOperationCompleted, userState);
        }
        
        private void OnIsAdminOperationCompleted(object arg) {
            if ((this.IsAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsAdminCompleted(this, new IsAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMsgByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Common_Message GetMsgByID(int MsgID) {
            object[] results = this.Invoke("GetMsgByID", new object[] {
                        MsgID});
            return ((Common_Message)(results[0]));
        }
        
        /// <remarks/>
        public void GetMsgByIDAsync(int MsgID) {
            this.GetMsgByIDAsync(MsgID, null);
        }
        
        /// <remarks/>
        public void GetMsgByIDAsync(int MsgID, object userState) {
            if ((this.GetMsgByIDOperationCompleted == null)) {
                this.GetMsgByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMsgByIDOperationCompleted);
            }
            this.InvokeAsync("GetMsgByID", new object[] {
                        MsgID}, this.GetMsgByIDOperationCompleted, userState);
        }
        
        private void OnGetMsgByIDOperationCompleted(object arg) {
            if ((this.GetMsgByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMsgByIDCompleted(this, new GetMsgByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRemotIP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRemotIP() {
            object[] results = this.Invoke("GetRemotIP", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRemotIPAsync() {
            this.GetRemotIPAsync(null);
        }
        
        /// <remarks/>
        public void GetRemotIPAsync(object userState) {
            if ((this.GetRemotIPOperationCompleted == null)) {
                this.GetRemotIPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRemotIPOperationCompleted);
            }
            this.InvokeAsync("GetRemotIP", new object[0], this.GetRemotIPOperationCompleted, userState);
        }
        
        private void OnGetRemotIPOperationCompleted(object arg) {
            if ((this.GetRemotIPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRemotIPCompleted(this, new GetRemotIPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLastMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetLastMsg(int MsgFIID) {
            object[] results = this.Invoke("GetLastMsg", new object[] {
                        MsgFIID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLastMsgAsync(int MsgFIID) {
            this.GetLastMsgAsync(MsgFIID, null);
        }
        
        /// <remarks/>
        public void GetLastMsgAsync(int MsgFIID, object userState) {
            if ((this.GetLastMsgOperationCompleted == null)) {
                this.GetLastMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastMsgOperationCompleted);
            }
            this.InvokeAsync("GetLastMsg", new object[] {
                        MsgFIID}, this.GetLastMsgOperationCompleted, userState);
        }
        
        private void OnGetLastMsgOperationCompleted(object arg) {
            if ((this.GetLastMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastMsgCompleted(this, new GetLastMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertMsg(string content, string IP, string Name, string title, int FuncIID, bool IsVisible) {
            object[] results = this.Invoke("InsertMsg", new object[] {
                        content,
                        IP,
                        Name,
                        title,
                        FuncIID,
                        IsVisible});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertMsgAsync(string content, string IP, string Name, string title, int FuncIID, bool IsVisible) {
            this.InsertMsgAsync(content, IP, Name, title, FuncIID, IsVisible, null);
        }
        
        /// <remarks/>
        public void InsertMsgAsync(string content, string IP, string Name, string title, int FuncIID, bool IsVisible, object userState) {
            if ((this.InsertMsgOperationCompleted == null)) {
                this.InsertMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertMsgOperationCompleted);
            }
            this.InvokeAsync("InsertMsg", new object[] {
                        content,
                        IP,
                        Name,
                        title,
                        FuncIID,
                        IsVisible}, this.InsertMsgOperationCompleted, userState);
        }
        
        private void OnInsertMsgOperationCompleted(object arg) {
            if ((this.InsertMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertMsgCompleted(this, new InsertMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteMsgByMsgID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteMsgByMsgID(int MsgID) {
            object[] results = this.Invoke("DeleteMsgByMsgID", new object[] {
                        MsgID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMsgByMsgIDAsync(int MsgID) {
            this.DeleteMsgByMsgIDAsync(MsgID, null);
        }
        
        /// <remarks/>
        public void DeleteMsgByMsgIDAsync(int MsgID, object userState) {
            if ((this.DeleteMsgByMsgIDOperationCompleted == null)) {
                this.DeleteMsgByMsgIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMsgByMsgIDOperationCompleted);
            }
            this.InvokeAsync("DeleteMsgByMsgID", new object[] {
                        MsgID}, this.DeleteMsgByMsgIDOperationCompleted, userState);
        }
        
        private void OnDeleteMsgByMsgIDOperationCompleted(object arg) {
            if ((this.DeleteMsgByMsgIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMsgByMsgIDCompleted(this, new DeleteMsgByMsgIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteMsgByFIID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteMsgByFIID(int MsgFIID) {
            object[] results = this.Invoke("DeleteMsgByFIID", new object[] {
                        MsgFIID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMsgByFIIDAsync(int MsgFIID) {
            this.DeleteMsgByFIIDAsync(MsgFIID, null);
        }
        
        /// <remarks/>
        public void DeleteMsgByFIIDAsync(int MsgFIID, object userState) {
            if ((this.DeleteMsgByFIIDOperationCompleted == null)) {
                this.DeleteMsgByFIIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMsgByFIIDOperationCompleted);
            }
            this.InvokeAsync("DeleteMsgByFIID", new object[] {
                        MsgFIID}, this.DeleteMsgByFIIDOperationCompleted, userState);
        }
        
        private void OnDeleteMsgByFIIDOperationCompleted(object arg) {
            if ((this.DeleteMsgByFIIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMsgByFIIDCompleted(this, new DeleteMsgByFIIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HasFIID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HasFIID(int FI_ID) {
            object[] results = this.Invoke("HasFIID", new object[] {
                        FI_ID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HasFIIDAsync(int FI_ID) {
            this.HasFIIDAsync(FI_ID, null);
        }
        
        /// <remarks/>
        public void HasFIIDAsync(int FI_ID, object userState) {
            if ((this.HasFIIDOperationCompleted == null)) {
                this.HasFIIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHasFIIDOperationCompleted);
            }
            this.InvokeAsync("HasFIID", new object[] {
                        FI_ID}, this.HasFIIDOperationCompleted, userState);
        }
        
        private void OnHasFIIDOperationCompleted(object arg) {
            if ((this.HasFIIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HasFIIDCompleted(this, new HasFIIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HasMsgID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HasMsgID(long MsgID) {
            object[] results = this.Invoke("HasMsgID", new object[] {
                        MsgID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HasMsgIDAsync(long MsgID) {
            this.HasMsgIDAsync(MsgID, null);
        }
        
        /// <remarks/>
        public void HasMsgIDAsync(long MsgID, object userState) {
            if ((this.HasMsgIDOperationCompleted == null)) {
                this.HasMsgIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHasMsgIDOperationCompleted);
            }
            this.InvokeAsync("HasMsgID", new object[] {
                        MsgID}, this.HasMsgIDOperationCompleted, userState);
        }
        
        private void OnHasMsgIDOperationCompleted(object arg) {
            if ((this.HasMsgIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HasMsgIDCompleted(this, new HasMsgIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFIID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public View_CommonFunction GetFIID(int ModID, int FunID, int FIOwnID) {
            object[] results = this.Invoke("GetFIID", new object[] {
                        ModID,
                        FunID,
                        FIOwnID});
            return ((View_CommonFunction)(results[0]));
        }
        
        /// <remarks/>
        public void GetFIIDAsync(int ModID, int FunID, int FIOwnID) {
            this.GetFIIDAsync(ModID, FunID, FIOwnID, null);
        }
        
        /// <remarks/>
        public void GetFIIDAsync(int ModID, int FunID, int FIOwnID, object userState) {
            if ((this.GetFIIDOperationCompleted == null)) {
                this.GetFIIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFIIDOperationCompleted);
            }
            this.InvokeAsync("GetFIID", new object[] {
                        ModID,
                        FunID,
                        FIOwnID}, this.GetFIIDOperationCompleted, userState);
        }
        
        private void OnGetFIIDOperationCompleted(object arg) {
            if ((this.GetFIIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFIIDCompleted(this, new GetFIIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGbook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetGbook(int fiid, int FIOwnID, string name, bool VisitType, bool CanWrite, bool CanDelete, bool IsPage, int everyNum) {
            object[] results = this.Invoke("GetGbook", new object[] {
                        fiid,
                        FIOwnID,
                        name,
                        VisitType,
                        CanWrite,
                        CanDelete,
                        IsPage,
                        everyNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetGbookAsync(int fiid, int FIOwnID, string name, bool VisitType, bool CanWrite, bool CanDelete, bool IsPage, int everyNum) {
            this.GetGbookAsync(fiid, FIOwnID, name, VisitType, CanWrite, CanDelete, IsPage, everyNum, null);
        }
        
        /// <remarks/>
        public void GetGbookAsync(int fiid, int FIOwnID, string name, bool VisitType, bool CanWrite, bool CanDelete, bool IsPage, int everyNum, object userState) {
            if ((this.GetGbookOperationCompleted == null)) {
                this.GetGbookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGbookOperationCompleted);
            }
            this.InvokeAsync("GetGbook", new object[] {
                        fiid,
                        FIOwnID,
                        name,
                        VisitType,
                        CanWrite,
                        CanDelete,
                        IsPage,
                        everyNum}, this.GetGbookOperationCompleted, userState);
        }
        
        private void OnGetGbookOperationCompleted(object arg) {
            if ((this.GetGbookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGbookCompleted(this, new GetGbookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGbookPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Gbook[] GetGbookPage(int PageId, int FIID, int everypagenum) {
            object[] results = this.Invoke("GetGbookPage", new object[] {
                        PageId,
                        FIID,
                        everypagenum});
            return ((Gbook[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGbookPageAsync(int PageId, int FIID, int everypagenum) {
            this.GetGbookPageAsync(PageId, FIID, everypagenum, null);
        }
        
        /// <remarks/>
        public void GetGbookPageAsync(int PageId, int FIID, int everypagenum, object userState) {
            if ((this.GetGbookPageOperationCompleted == null)) {
                this.GetGbookPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGbookPageOperationCompleted);
            }
            this.InvokeAsync("GetGbookPage", new object[] {
                        PageId,
                        FIID,
                        everypagenum}, this.GetGbookPageOperationCompleted, userState);
        }
        
        private void OnGetGbookPageOperationCompleted(object arg) {
            if ((this.GetGbookPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGbookPageCompleted(this, new GetGbookPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Gbook[] GetAllList(int FIID) {
            object[] results = this.Invoke("GetAllList", new object[] {
                        FIID});
            return ((Gbook[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllListAsync(int FIID) {
            this.GetAllListAsync(FIID, null);
        }
        
        /// <remarks/>
        public void GetAllListAsync(int FIID, object userState) {
            if ((this.GetAllListOperationCompleted == null)) {
                this.GetAllListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllListOperationCompleted);
            }
            this.InvokeAsync("GetAllList", new object[] {
                        FIID}, this.GetAllListOperationCompleted, userState);
        }
        
        private void OnGetAllListOperationCompleted(object arg) {
            if ((this.GetAllListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllListCompleted(this, new GetAllListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSingleList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Gbook GetSingleList(int MsgId) {
            object[] results = this.Invoke("GetSingleList", new object[] {
                        MsgId});
            return ((Gbook)(results[0]));
        }
        
        /// <remarks/>
        public void GetSingleListAsync(int MsgId) {
            this.GetSingleListAsync(MsgId, null);
        }
        
        /// <remarks/>
        public void GetSingleListAsync(int MsgId, object userState) {
            if ((this.GetSingleListOperationCompleted == null)) {
                this.GetSingleListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSingleListOperationCompleted);
            }
            this.InvokeAsync("GetSingleList", new object[] {
                        MsgId}, this.GetSingleListOperationCompleted, userState);
        }
        
        private void OnGetSingleListOperationCompleted(object arg) {
            if ((this.GetSingleListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSingleListCompleted(this, new GetSingleListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Common_Message {
        
        private int msg_IDField;
        
        private string msg_TitleField;
        
        private System.Nullable<int> msg_FIIDField;
        
        private string msg_NameField;
        
        private string msg_IPField;
        
        private string msg_ContentField;
        
        private System.Nullable<System.DateTime> msg_CreateTimeField;
        
        private System.Nullable<bool> msg_IsVisibleField;
        
        private System.Nullable<int> msg_tempBlogUseridField;
        
        private string msg_UserUrlField;
        
        /// <remarks/>
        public int Msg_ID {
            get {
                return this.msg_IDField;
            }
            set {
                this.msg_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Msg_Title {
            get {
                return this.msg_TitleField;
            }
            set {
                this.msg_TitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Msg_FIID {
            get {
                return this.msg_FIIDField;
            }
            set {
                this.msg_FIIDField = value;
            }
        }
        
        /// <remarks/>
        public string Msg_Name {
            get {
                return this.msg_NameField;
            }
            set {
                this.msg_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Msg_IP {
            get {
                return this.msg_IPField;
            }
            set {
                this.msg_IPField = value;
            }
        }
        
        /// <remarks/>
        public string Msg_Content {
            get {
                return this.msg_ContentField;
            }
            set {
                this.msg_ContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Msg_CreateTime {
            get {
                return this.msg_CreateTimeField;
            }
            set {
                this.msg_CreateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Msg_IsVisible {
            get {
                return this.msg_IsVisibleField;
            }
            set {
                this.msg_IsVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Msg_tempBlogUserid {
            get {
                return this.msg_tempBlogUseridField;
            }
            set {
                this.msg_tempBlogUseridField = value;
            }
        }
        
        /// <remarks/>
        public string Msg_UserUrl {
            get {
                return this.msg_UserUrlField;
            }
            set {
                this.msg_UserUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Gbook {
        
        private int msg_IDField;
        
        private string msg_TitleField;
        
        private System.Nullable<int> msg_FIIDField;
        
        private string msg_NameField;
        
        private string msg_IPField;
        
        private string msg_ContentField;
        
        private System.Nullable<System.DateTime> msg_CreateTimeField;
        
        private System.Nullable<bool> msg_IsVisibleField;
        
        private System.Nullable<int> msg_tempBlogUseridField;
        
        private string msg_UserUrlField;
        
        /// <remarks/>
        public int Msg_ID {
            get {
                return this.msg_IDField;
            }
            set {
                this.msg_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Msg_Title {
            get {
                return this.msg_TitleField;
            }
            set {
                this.msg_TitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Msg_FIID {
            get {
                return this.msg_FIIDField;
            }
            set {
                this.msg_FIIDField = value;
            }
        }
        
        /// <remarks/>
        public string Msg_Name {
            get {
                return this.msg_NameField;
            }
            set {
                this.msg_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Msg_IP {
            get {
                return this.msg_IPField;
            }
            set {
                this.msg_IPField = value;
            }
        }
        
        /// <remarks/>
        public string Msg_Content {
            get {
                return this.msg_ContentField;
            }
            set {
                this.msg_ContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Msg_CreateTime {
            get {
                return this.msg_CreateTimeField;
            }
            set {
                this.msg_CreateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Msg_IsVisible {
            get {
                return this.msg_IsVisibleField;
            }
            set {
                this.msg_IsVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Msg_tempBlogUserid {
            get {
                return this.msg_tempBlogUseridField;
            }
            set {
                this.msg_tempBlogUseridField = value;
            }
        }
        
        /// <remarks/>
        public string Msg_UserUrl {
            get {
                return this.msg_UserUrlField;
            }
            set {
                this.msg_UserUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class View_CommonFunction {
        
        private int mod_IDField;
        
        private string mod_NameField;
        
        private int fI_IDField;
        
        private int fI_FuncIDField;
        
        private System.Nullable<int> fI_OwnerIDField;
        
        private System.Nullable<int> fI_MODIDField;
        
        private string func_NameField;
        
        private long func_IDField;
        
        private System.Nullable<bool> fUNC_ISROOTField;
        
        /// <remarks/>
        public int Mod_ID {
            get {
                return this.mod_IDField;
            }
            set {
                this.mod_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Mod_Name {
            get {
                return this.mod_NameField;
            }
            set {
                this.mod_NameField = value;
            }
        }
        
        /// <remarks/>
        public int FI_ID {
            get {
                return this.fI_IDField;
            }
            set {
                this.fI_IDField = value;
            }
        }
        
        /// <remarks/>
        public int FI_FuncID {
            get {
                return this.fI_FuncIDField;
            }
            set {
                this.fI_FuncIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FI_OwnerID {
            get {
                return this.fI_OwnerIDField;
            }
            set {
                this.fI_OwnerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FI_MODID {
            get {
                return this.fI_MODIDField;
            }
            set {
                this.fI_MODIDField = value;
            }
        }
        
        /// <remarks/>
        public string Func_Name {
            get {
                return this.func_NameField;
            }
            set {
                this.func_NameField = value;
            }
        }
        
        /// <remarks/>
        public long Func_ID {
            get {
                return this.func_IDField;
            }
            set {
                this.func_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> FUNC_ISROOT {
            get {
                return this.fUNC_ISROOTField;
            }
            set {
                this.fUNC_ISROOTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void AddAdminCompletedEventHandler(object sender, AddAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void IsAdminCompletedEventHandler(object sender, IsAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetMsgByIDCompletedEventHandler(object sender, GetMsgByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMsgByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMsgByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Common_Message Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Common_Message)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetRemotIPCompletedEventHandler(object sender, GetRemotIPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRemotIPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRemotIPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetLastMsgCompletedEventHandler(object sender, GetLastMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void InsertMsgCompletedEventHandler(object sender, InsertMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void DeleteMsgByMsgIDCompletedEventHandler(object sender, DeleteMsgByMsgIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMsgByMsgIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMsgByMsgIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void DeleteMsgByFIIDCompletedEventHandler(object sender, DeleteMsgByFIIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMsgByFIIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMsgByFIIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void HasFIIDCompletedEventHandler(object sender, HasFIIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasFIIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HasFIIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void HasMsgIDCompletedEventHandler(object sender, HasMsgIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasMsgIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HasMsgIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetFIIDCompletedEventHandler(object sender, GetFIIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFIIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFIIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public View_CommonFunction Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((View_CommonFunction)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetGbookCompletedEventHandler(object sender, GetGbookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGbookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGbookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetGbookPageCompletedEventHandler(object sender, GetGbookPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGbookPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGbookPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Gbook[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Gbook[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetAllListCompletedEventHandler(object sender, GetAllListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Gbook[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Gbook[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetSingleListCompletedEventHandler(object sender, GetSingleListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSingleListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSingleListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Gbook Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Gbook)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591